### ISSUE TITLE
Remove nug comments not under stickied comment

### ISSUE THREAD

**Issue by max-landry** [Xeoth/GoldenNuggetBot#26]
Would prevent clutter, seems to be a common mistake

**Comment by xeoth** [comment]
Maybe use automod for that

**Comment by max-landry** [comment]
Though it could be done, it might be easier to do via the bot. If someone wants to add it to automod i'm not opposed

**Comment by xeoth** [comment]
```
type: comment
is_top_level: true
body (starts-with): ["!nug", "!nugget", "!gold"]
action: remove
```

**Comment by max-landry** [comment]
Just added this code to automod, closing this issue
