### ISSUE TITLE
Better output to console

### ISSUE THREAD

**Issue by max-landry** [Xeoth/GoldenNuggetBot#32]
Currently the bot sends various messages to console when it completes actions. This, however, should be better and more consistently done

- the still running check should send a message once every 5 minutes, as opposed to once every 50 minutes (which is once every minute in current code due to placeholder)
- all logging should display date and time
- detection of comment/submissions should send a link to the respective item and the author's name
- logging should be more descriptive
- no output should be sent to console for the bot detecting its own comments/submissions

I will work on this later

**Comment by xeoth** [comment]
Maybe make a `log` class so we can do stuff like `log.info()`, `log.error()` and such?
