### ISSUE TITLE
database/check_comment + check_post not working

### ISSUE THREAD

**Issue by max-landry** [Xeoth/GoldenNuggetBot#33]
Unsure if this was ever fixed, but when I last tried it this wasn't working in python 3.7.4: comments/posts appeared to be already in database when checking the stream here

![image](https://user-images.githubusercontent.com/46831500/85212585-3d7bb980-b322-11ea-9450-288c156a3f3f.png)

, resulting in no bot actions ever occurring. This should be fixed as it prevents the bot from working. I suspect the culprit is how it acts on an empty tuple, but as you know I am not as experienced with python

**Comment by l-p-d** [comment]
What does `not submission` do? I've never understood it's purpose

**Comment by xeoth** [comment]
I guess it's there for when a submission is deleted but the bot picks it up anyway, so it doesn't error out. I'm not sure though.

**Comment by l-p-d** [comment]
We'd want `not submission.author` for that anyway; I'll work on this tomorrow.

**Comment by max-landry** [comment]
I wrote that code and looked at the docs: this is necessary, leave that as is
     When using the stream how we are using it, it'll return None if nothing new has been posted/commented since last check. Making it ```not submission.author``` will crash the bot, so will removing it.
     For context, this was ```if submission is None``` before
@Xeoth @lpd11

**Comment by l-p-d** [comment]
> results in no bot actions occurring 

> leave as is

Confused here, do you mean change it to explicitly be `!= None`(better practice than `is not None`, and does the same thing in this instance).

**Comment by max-landry** [comment]
Leave the ```if not submission``` part, change the code in the database file to fix the return value of ```db.check_post/comment```
