### ISSUE TITLE
!bal command needs improvement

### ISSUE THREAD

**Issue by max-landry** [Xeoth/GoldenNuggetBot#36]
This command, while it seems fine, needs some minor improvement:

- users not in database that try to check balance should be prompted with the default database values (0 received nuggets and 3 award nuggets) rather than stating the aren't in the database: sorta an unhelpful response
- reply formatting should be improved:

![image](https://user-images.githubusercontent.com/46831500/85212875-225e7900-b325-11ea-99ed-a69330f2f413.png)

    - these should be on new lines if not already
    - number of nuggets should probably be bolded

**Comment by l-p-d** [comment]
They're already on new lines, triple quotes indicate a multi-line string. But yes, I agree with your other points.
