### ISSUE TITLE
[Important] Mod only commands under stickied post in r/minecraftmeme

### ISSUE THREAD

**Issue by max-landry** [Xeoth/GoldenNuggetBot#42]
This would include things such as resetting the database, adjusting award amounts (such as when users are supposed to gain 3 nuggets upon theme switch), etc. Very necessary

Likely easiest way to do this is to make a command to allow custom SQL code to be executed from reddit comments, and someone like @Xeoth would do that. Could potentially solve a lot of issues potentially arising from cheating, etc

**Comment by xeoth** [comment]
Totally doable, but I have doubts at SQL code being executed from Reddit comments. I can just ssh to the server and do stuff in the DB there. Commands like `!reset [username]`, `!set [username] [amount]` or `!ban [username]` would be on point though.

**Comment by max-landry** [comment]
We need to have a way to add 3 award nugs to everyone. Also when i tried editing the DB on my side manually, it locked the bot from doing any database stuff and crashed it, so i'm not sure

**Comment by xeoth** [comment]
I'm definitely gonna do the 3 commands mentioned above. Do we want anything else?
