### ISSUE TITLE
Default nugget values should be none received and 3 awarded disregarding testing

### ISSUE THREAD

**Issue by max-landry** [Xeoth/GoldenNuggetBot#54]
This is incredibly inconsistent in the code. I'm unsure where 5 came from but as far as I know the default was said to be 3. The 10k is fine if its for testing but it needs to be changed before release. If we want different values we should discuss them in staff chat, not willy nilly. Someone please fix

**Comment by xeoth** [comment]
#52 introduces `DEF_AV_NUGS` to .env so we can go from there.
