### ISSUE TITLE
Leaderboard

### ISSUE THREAD

**Issue by xeoth** [Xeoth/GoldenNuggetBot#9]
We should leave that for the end. A leaderboard showing listing top 10 nugget owners. Do it either by making a webapp or send leaderboard in response to a message sent to the bot

**Comment by l-p-d** [comment]
Just have it as a command, people don't want to click offsite links.

Also it's a lot of effort to make a whole web app for it.

**Comment by xeoth** [comment]
~~I can do it~~ yeah you're probably right a command will do
